spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    favicon:
      enabled: true
server:
  session:
    'tracking-modes': cookie

game:
  config:
    dice:
      min: 1
      max: 6
    numof:
      player: 4
      aeroplane: 4
