spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    favicon:
      enabled: true
server:
  session:
    'tracking-modes': cookie

websocket:
  gameroom:
    config:
      numof:
        player: 4
  aeroplanechess:
    config:
      dice:
        min: 1
        max: 6
      numof:
        aeroplane: 4